name: Build and push an image
description: Build and push an image to ghcr registry

inputs:
  imageName:
    description: Name of the docker image
    required: true
  token:
    required: true
    description: PAT Token

outputs:
  fullImageName:
    description: Full name of the docker image ex. ghcr.io/b-zago/app/webserver
    value: ${{ steps.outgen.outputs.fullImageName }}
  tag:
    description: Docker image tag to replace current one
    value: ${{ steps.outgen.outputs.sha }}

runs:
  using: composite
  steps:
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: SHA and outputs generator
      shell: bash
      id: outgen
      run: |
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "fullImageName=ghcr.io/${{ github.repository }}/${{ inputs.imageName }}" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ steps.outgen.outputs.fullImageName }}:latest
          ${{ steps.outgen.outputs.fullImageName }}:${{ steps.outgen.outputs.sha }}
