on:
  workflow_call:
    inputs:
      imageName:
        type: string
        required: true
      ignoreMissing:
        type: string
        default: "false"
        description: Should missing values files be ignored on k3s-bump. Will exit with code 0 if 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true

      - uses: b-zago/actions/build-push-ghcr@v1
        id: buildPush
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: ${{ inputs.imageName }}

      - uses: b-zago/actions/k3s-bump@v1
        with:
          patToken: ${{ secrets.PAT_TOKEN }}
          fullImageName: ${{ steps.buildPush.outputs.fullImageName }}
          tag: ${{ steps.buildPush.outputs.tag }}
          ignoreMissing: ${{ inputs.ignoreMissing }}
